// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Omq-UhWHUonlDyQ4-MaBnecU136OREY',
    appId: '1:325985892120:web:b457a0717ccee196d5106d',
    messagingSenderId: '325985892120',
    projectId: 'doancuoiky-544bc',
    authDomain: 'doancuoiky-544bc.firebaseapp.com',
    storageBucket: 'doancuoiky-544bc.appspot.com',
    measurementId: 'G-0TG4ZYWGVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOBvytu0qK4RZJ140j9S2wGauAfyzM5bo',
    appId: '1:325985892120:android:0de7338333f673a9d5106d',
    messagingSenderId: '325985892120',
    projectId: 'doancuoiky-544bc',
    storageBucket: 'doancuoiky-544bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxI4iTFcNaq2JbSzMJQfu4EIJOl8xbjVQ',
    appId: '1:325985892120:ios:a63a57557e86bf97d5106d',
    messagingSenderId: '325985892120',
    projectId: 'doancuoiky-544bc',
    storageBucket: 'doancuoiky-544bc.appspot.com',
    iosBundleId: 'com.example.doAnCuoiKy',
  );
}
